# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 408a63eb54aca3f11790c819a450182e88c2a4afb6164d38b0820199ec14416c5db88ac7daeb94ee55ceeed0ec3c4be6a7d453003329d4a56c868fe4741c246a

test:
  secret_key_base: 0e83ae4096310e0c31cb0269f28bc934bed453b0fa0b3c969cce7c3bf1daa46817cbd77c535916e704a13996cb0077b2f6ed9326e5136983b4c697c938599486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
